name: 'DVC Benchmarks'
description: 'Run dvc benchmarks'
inputs:
  pytest_options:
    description: 'pytest options'
    default: ""
    required: false
  python-version:
    default: "3.10"
    description: "python version to install"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: pr
        fetch-depth: 0

    - uses: actions/checkout@v3
      with:
        path: base
        ref: "${{ github.event.pull_request.base.sha }}"
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
          python-version: "${{ inputs.python-version }}"
          id: py
          cache: pip
          cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - run: |
        python -m pip install --upgrade pip wheel
        pip install -r ${{ github.action_path }}/requirements.txt
      if: steps.py.outputs.cache-hit != 'true'
      shell: bash

    - uses: syphar/restore-virtualenv@v1
      id: venv
      with:
        requirement_files: base/pyproject.toml

    - name: install dvc from base branch
      working-directory: base
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: pip install .

    - name: run benchmarks for base
      shell: bash
      working-directory: "${{ github.action_path }}"
      env:
        DVC_TEST: "true"
      run: |
        ${{ steps.venv.outputs.virtualenv-directory}}/bin/dvc --version
        ${{ steps.py.outputs.python-path}} -m pytest \
          --benchmark-autosave \
          --dvc-bin ${{ steps.venv.outputs.virtualenv-directory}}/bin/dvc \
          ${{ inputs.pytest_options }} tests/benchmarks

    - name: install dvc from pull request
      working-directory: pr
      shell: bash
      run: pip install .

    - name: run benchmarks for PR
      shell: bash
      working-directory: "${{ github.action_path }}"
      env:
        DVC_TEST: "true"
        PY_COLORS: "1"
      run: |
        ${{ steps.venv.outputs.virtualenv-directory}}/bin/dvc --version
        ${{ steps.py.outputs.python-path}} -m pytest \
          --benchmark-autosave \
          --benchmark-compare \
          --benchmark-compare-fail=median:5% \
          --benchmark-group-by name \
          --dvc-bin ${{ steps.venv.outputs.virtualenv-directory}}/bin/dvc \
          ${{ inputs.pytest_options }} tests/benchmarks
