stages:
  convert_tags:
    cmd: asv check && python revs_to_sha.py
    deps:
    - revisions.txt
    - revs_to_sha.py
    outs:
    - hashes.txt
  run_benchmarks:
    cmd: asv update && asv run HASHFILE:hashes.txt --skip-existing-successful --profile --show-stderr
    deps:
    - hashes.txt
    outs:
    - results:
        persist: true
        cache: false
