stages:
  convert_tags:
    cmd: python tags_to_sha.py
    deps:
    - tags.txt
    - tags_to_sha.py
    outs:
    - hashes.txt
  run_benchmarks:
    cmd: asv update && asv run HASHFILE:hashes.txt --skip-existing-successful --profile --show-stderr
    deps:
    - hashes.txt
    outs:
    - results:
        persist: true
