name: daily run
on:
  schedule:
    - cron: '0 0 * * *'

env:
  DVC_TEST: "true"

jobs:
  build:
    timeout-minutes: 4320
    name: run benchmarks
    runs-on: dvc-runner
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r requirements.txt
      - name: setup asv machine
        run: python write_asv_machine.py
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: download data
        run: dvc pull data/cats_dogs.dvc
      - name: download existing results
        run: aws s3 cp --recursive s3://dvc-bench/latest_results results
      - name: run benchmarks on latest master
        run: asv run --show-stderr
      - name: upload raw results
        uses: actions/upload-artifact@v2
        with:
          name: results-aws-runner
          path: results
      - name: cleanup tmp
        run: rm -rf /tmp/*
  publish:
    name: join results and publish
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r requirements.txt
      - name: download ubuntu results
        uses: actions/download-artifact@v2
        with:
          name: results-aws-runner
          path: /tmp/results-ubuntu
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: download existing results
        run: aws s3 cp --recursive s3://dvc-bench/latest_results results
      - name: join results
        run: |
          cp -r /tmp/results-ubuntu/linux* results/
      - name: create static html
        run: asv update && asv publish
      - name: upload new results
        run: aws s3 cp --recursive results s3://dvc-bench/latest_results
      - name: deploy new benchmarks to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
