name: daily regression check
# schedule 8 hours after nightly build
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  report_regressions:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r requirements.txt
      - name: clone dvc repo
        run: asv check
      - name: detect regression and prepare issue template
        run: python parse_feed.py
      - name: check issue template existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
            files: ".github/ISSUE_TEMPLATE.md"
      - name: create issue
        if: steps.check_files.outputs.files_exists == 'true'
        id: create-issue
        uses: JasonEtco/create-an-issue@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ping slack
        if: steps.check_files.outputs.files_exists == 'true'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: ${{ steps.create-issue.outputs.url }}
            SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            SLACK_USERNAME: "regressionBot"
